---
- name: Install yq
  get_url:
    url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    dest: /usr/local/bin/yq
    mode: 0755
  become: true

- name: Download Gitpod installer
  get_url:
    url: https://github.com/gitpod-io/gitpod/releases/download/2022.01/gitpod-installer-linux-amd64
    dest: /usr/local/bin/gitpod-installer
    checksum: sha256:0a03b767fcc4be1806ddbac799e49e0b22f99a578ceed6461296952f2db9c1dd
    mode: 0755
  become: true

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  become: true
  loop:
    - /gitpod

- name: Generate Gitpod config
  shell: gitpod-installer init > /gitpod/gitpod-config.yaml

- name: Remove uid and resource version from manifests files
  shell: |
    for f in /gitpod/manifests/*.yaml; do
      yq eval --inplace "del(.metadata.uid)" "$f"
      yq eval --inplace "del(.metadata.resourceVersion)" "$f"
    done
  args:
    executable: /bin/bash

- name: Check if auth-provider-public-github.yaml exists
  stat:
    path: "/gitpod/manifests/auth-provider-public-github.yaml"
  register: auth_provider_public_github_yaml

- name: Add auth-provider-public-github.yaml to Gitpod config
  command: "yq eval --inplace '.authProviders += [{\"kind\": \"secret\", \"name\": \"auth-provider-public-github\"}]' /gitpod/gitpod-config.yaml"
  when: auth_provider_public_github_yaml.stat.exists
