apiVersion: v1
kind: Secret
metadata:
  name: clouddns-dns01-solver-svc-acct
  namespace: cert-manager
data:
  #key: "dns_solver_serviceaccount_key.privateKeyData"
  key: "{{ gcp.cred_content | b64encode }}"
