---
- name: Test Localhost
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    nodes_count: 3

  tasks:
    - name: Say hello
      lineinfile:
        path: /tmp/test.txt
        line: "Count: {{nodes_count}}, Item: {{ item }}"
        insertbefore: BOF
        create: yes
      loop: "{{ range(0, nodes_count) | list }}"