---
gcp:
  project: clu-self-hosted-playground
  cred_content: "{{ lookup('file', '/tmp/service-account.json') }}"
  bucket_name: clu-gcp-k3s
  region: europe-west3
  zone: europe-west3-a
  machine_type: c2-standard-4
